### ISSUE TITLE
GCC Module not found

### ISSUE THREAD

**Issue by MattBixley** [nesi/rstudio_on_nesi#14]
within RStudio when install.packages() called there is an issue with GCC and it's commands not being visible
Error thrown example
/bin/sh: gcc: command not found

Also g++ command.

**Comment by jennan** [comment]
Hi Matt,

Have you tried to load GCC module using the prelude.bash mechanism? Please let us know if this doesn't fix your issue.

FYI @CallumWalley

**Comment by CallumWalley** [comment]
Fixed by prelude.bash
